# Use node:-alpine as the base image to run tests/building
# Right now only a single node version is supported
image: node:14.15-alpine

include:
  # See template for docs
  # https://gitlab.unueng.com/gitlab-ci/templates/tree/master/npm
  - project: 'gitlab-ci/templates'
    # We use master instead of branches so we can automatically roll out updates
    # That are not breaking changes. We do versioning on a file level
    # If these break a user can manually go back and update the ref tag to a previous commit
    ref: master
    file: '/npm/0.2-template.yml'

services:
  - name: mongo:4.0
    alias: mongodb
  - name: rabbitmq:3.8-management-alpine
    alias: rabbitmq

# Verify our code works with multiple node versions
test-node16:
  image: node:16.14-alpine
  stage: test
  script:
  - npm i
  - npm run test

